### ISSUE TITLE
[DevReport] Translations get reset on server start

### ISSUE THREAD

**Issue by Josh-65** [ToberoCat/ImprovedFactions_new#35]
When I edit the translation file and restart the server the file gets replace with defaults.

**Comment by ToberoCat** [comment]
Language file auto fix will be added with next dev uild

**Comment by Josh-65** [comment]
I dont think the auto fix works correctly. The "fixed" file is completely diffrent from the es_us.xml file on github.

**Comment by ToberoCat** [comment]
Yeah, this issue is because the original files have been writen by me by hand, while the fixed files will just get all missing values added and writen to disk.

This will give a sh*t about formatting, as long as all values I gave the computer are represented in it.
Will try to mkae the hand writen ones look like the computer generated, so that there is no difference anymore
