### ISSUE TITLE
[DevReport] chunks can be claimed in disabled worlds

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#64]
I have faction worlds in the enabled worlds section of the config and I can still claim chunks in any world.

**Comment by ToberoCat** [comment]
Yeah, that makes sense, but I can't make them all into a single file.

A example why I can't: let's say you have 100.000 claimed chunks. You have 20 active players wandering around. All of them walk into a new chunk. With this action, the plugin will lookup in cache if there's a loaded chunk file. If not, it will try to load one. Let's say file 10_0 is getting loaded. This will cost the server less time when I have a single file for each chunk, as if I had a world chunk only file, that's maybe 1mb big, because to be ram efficient, I won't keep the entire file loaded, which would make loading a chunk much laggy.

But I also see that this file spam costs much disk space, that's why I'll be creating chunk groups. These chunk groups can have variable size, negative one would result in the entire world being put into a single file. A number like 100 will group them on the x and y into groups of 100. This would mean, that when a player walks into a new chunk group, he will load only the chunk group file.

I have to design this system for bigger chunk saves, as I'm planing to add moduled to them, just like I did with factions, so that extensions can save data chunk wise, allowing me to make districts with their own permissions

**Comment by ToberoCat** [comment]
Okay, will see what's going one here

**Comment by Josh65-2201** [comment]
Closing since Luckperms has world only permissions and I think it's better for this to be handle by the permission manager.
