### ISSUE TITLE
[DevReport] Have factions claimed chunk in one file

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#66]
Instead of making lots of files with the chunk coordinates. Making a file name with the world and then add faction registry name in that file with the claimed chunks in would be faster to reset or see what faction has a chunk outside of the game. 
Would also help save disk space as each file is like 12b at most and a disk minimize size is usually 4kb (each file is effectively this big on the disk always, wasting space)

File structure would be `chunks/worldname.yml` containing
factionname:
   00
   0-1
   -1-1
factionname2:
   00
   0-1
   -1-1

**Comment by ToberoCat** [comment]
Yeah, that makes sense, but I can't make them all into a single file.

A example why I can't: let's say you have 100.000 claimed chunks. You have 20 active players wandering around. All of them walk into a new chunk. With this action, the plugin will lookup in cache if there's a loaded chunk file. If not, it will try to load one. Let's say file 10_0 is getting loaded. This will cost the server less time when I have a single file for each chunk, as if I had a world chunk only file, that's maybe 1mb big, because to be ram efficient, I won't keep the entire file loaded, which would make loading a chunk much laggy.

But I also see that this file spam costs much disk space, that's why I'll be creating chunk groups. These chunk groups can have variable size, negative one would result in the entire world being put into a single file. A number like 100 will group them on the x and y into groups of 100. This would mean, that when a player walks into a new chunk group, he will load only the chunk group file.

I have to design this system for bigger chunk saves, as I'm planing to add moduled to them, just like I did with factions, so that extensions can save data chunk wise, allowing me to make districts with their own permissions

**Comment by Josh-65** [comment]
Would a databased file work? There are local versions of SQL.
https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb#:~:text=An%20instance%20of%20SQL%20Server%20Express%20LocalDB%20is%20an%20instance,is%20limited%20to%20its%20owner.

**Comment by ToberoCat** [comment]
Yes, mysql is even the supported / prefered way to use this plugin, as it provides faster speed.

**Comment by ToberoCat** [comment]
But I'll take a look at the local files

**Comment by Josh65-2201** [comment]
Fixed in v2 stable dev build
