### ISSUE TITLE
[DevReport] Disabled worlds use wrong languge key

### ISSUE THREAD

**Issue by Josh65-2201** [ToberoCat/ImprovedFactions_new#85]
Running `/f claim` in a blacklisted world requests `base.exceptions.cant-claim-this-chunk` rather then `base.exceptions.cant-claim-in-this-world`

**Comment by ToberoCat** [comment]
This is a decision I've made to reduce code complexity. Now I just have a part of my code evalute if the chunk can get claimed, returning true or false.
Because these just allow for two states, I've generalized the error message into just saying that you can't claim the chunk.

Should I add back at least the message for the black listed world or can it stay like that?

**Comment by Josh65-2201** [comment]
I'm fine with it as is just didn't think it was intentional
